---
name: CI
on:
  pull_request:
  push:
    branches: [main, 'release-*']
    tags: ['v*']

permissions:
  contents: read

jobs:
  test:
    name: Test actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Validate Workflows and Custom Actions
        uses: mpalmer/action-validator@76a805bbfcba3506d6cdb4bba1810ab504e0d72b # v0.9.0
        with:
          patterns: |-
            .github/workflows/*.yml
            build/action.yml
            publish_main/action.yml
            publish_release/action.yml
